/**
 * UI chrome: section headings and link text. Lives here so components hold no
 * copy at all — every string the page renders comes from the content layer.
 */
export const labels = {
  selectedWork: "Selected work",
  background: "Background",
  contact: "Contact",
  stack: "Stack",
  problem: "Problem",
  approach: "Approach",
  links: "Links",
  viewCaseStudy: "View case study",
  notes: "Notes",
  readingTimeSuffix: "min read",
  colophon: "colophon",
  colophonTitle: "Colophon",
  process: "Process",
  numbers: "Numbers",
  principles: "Principles",
  pipeline: "Pipeline",
  pipelineHint:
    "Select a stage for what it does, the artifact it writes and how it fails.",
  /* Shell-prompt chrome for the hero's "currently" line. */
  promptSymbol: "$",
  promptCurrently: "currently:",
  pipelineRun: "Pipeline run",
  simulateFailure: "Simulate failure",
  humanApproval: "human approval",
  /* Status wording. "not run" rather than "skipped": on a resume it is the
     upstream stages that get skipped, while these never executed at all. */
  statusComplete: "complete",
  statusFailed: "failed",
  statusNotRun: "not run",
  visited: "visited",
  backToHome: "Back to home",

  /* Embedded case-study demos. */
  inspector: "Analysis",
  inspectorHint:
    "Explore an analysis — hover a lane, click for densitometry, open the provenance record.",
  funnel: "Pipeline",
  funnelHint:
    "Select a stage for what it does and the artifact it reads or writes. Counts are the committed gold set, not a model run.",
  /* Shown only when the demo's committed artifacts could not be loaded. */
  placeholderBanner: "Placeholder data",

  /* Progressive disclosure: the reasoning behind a scannable summary. */
  whyToggle: "why",

  /* Link label the case-study header pulls up next to the title. */
  repository: "Repository",

  /* Embedded sections. */
  qcEffect: "What QC is for",
  qcEffectHint:
    "Mean absolute error over three subsets of the same run — everything matched, then progressively only the bands whose ground truth is clean.",
  sweeps: "Parameter sweeps",
  sweepsHint:
    "The measurements behind the shipped configuration. Select a parameter; the shipped value is marked.",
  goldRecords: "The gold set",
  goldRecordsHint:
    "A hand-labeled record, and the deterministic quote check running against the checker's own fixtures.",
  realRun: "The first real-data run",
  realRunHint: "Nineteen CC-BY crops, and what the pipeline did with them.",

  /* Sweep explorer. */
  sweepSelector: "Parameter sweeps",
  shipped: "shipped",
  sweepCaption:
    "Generated by evals/sweep.py and re-measured by --check in CI. Read from evals/dev_sweeps.json at",
  qcChartCaption: "From the intensity-recovery table at",

  /* Real-data run. */
  refusalGrid: "CC-BY crops",
  refused: "refused",

  /* Gold-record inspector. */
  inspectorTabs: "Gold set views",
  tabRecords: "records",
  tabChecker: "quote checker",
  recordSelector: "Gold records",
  quoteVerbatim: "verbatim match",
  quoteAbsent: "no match",
  quoteAbsentDetail:
    "not present in the source, so the record fails rather than warning",
  noWindowNote:
    "Quotes are shown without the surrounding source text: the abstracts are not committed to that repository, and a quote is shown with its verification status rather than fetched from anywhere.",
  checkerFixtureNote:
    "Matched live, in the browser, against the checker's own test fixtures — the repository's text, not a publisher's:",
} as const;
